# Generated by Django 2.1.7 on 2019-08-19 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_recognition_result_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.TextField(max_length='255')),
                ('type_probability', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RenameField(
            model_name='recognition',
            old_name='created',
            new_name='recognition_time',
        ),
        migrations.RemoveField(
            model_name='recognition',
            name='type_name',
        ),
        migrations.RemoveField(
            model_name='recognition',
            name='type_probability',
        ),
        migrations.AddField(
            model_name='probability',
            name='recognition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.Recognition'),
        ),
    ]
