# Generated by Django 2.1.7 on 2019-08-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_auto_20190819_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probability',
            name='recognition',
        ),
        migrations.AddField(
            model_name='recognition',
            name='result_json',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Probability',
        ),
    ]
